#!/usr/bin/env python

from __future__ import division
import rospy
from std_msgs.msg import Int64
from single_integrator.read_matrix import *

def main():
    rospy.init_node('simulation_time')
    pub_t = rospy.Publisher('~tick', Int64)
    T = load_matrix_from_file('T.txt')
    T = T[1, 0]
    r = rospy.Rate(1/T)
    i = 0
    while not rospy.is_shutdown():
        pub_t.publish(i)
        i+= 1
        r.sleep()

if __name__ == "__main__":
    main()
