#!/usr/bin/env python

from __future__ import division
import os
import rospy
from std_msgs.msg import Int64
from dinsdale_system.read_matrix import *

def main():
    rospy.init_node('simulation_time')
    pub_t = rospy.Publisher('~tick', Int64)
    loc, f = os.path.split(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(loc, "src/dinsdale_system/input_parameters/T.txt")
    times = load_matrix_from_file(path)
    T, T_final = times[1, 0], times[2, 0]
    r = rospy.Rate(1/T)
    i = 0
    i_final = T_final/T
    while not rospy.is_shutdown() or i >= i_final:
        pub_t.publish(i)
        i+= 1
        r.sleep()

if __name__ == "__main__":
    main()
