#!/usr/bin/env python


"""
Usage:
  node_controller <node_number> <node_type>
"""


from __future__ import division
import sys
sys.dont_write_bytecode = True
import os
import rospy
import rosbag
import numpy as np
import importlib
from rospy.numpy_msg import numpy_msg
PKG = 'dinsdale'
import roslib; roslib.load_manifest(PKG)
from dinsdale.msg import Floats
from dinsdale_system.tools.read_matrix import *


# ----------------------------------------------------------------


class ControllerNode:
    """ ROS wrapper for a Controller object """


    def __init__(self, node_number, node_type):
        """ Initialize ROS node """

        # Setup publishers and subscribers
        self.pub_u = rospy.Publisher('~u', numpy_msg(Floats))
        loc, f = os.path.split(os.path.dirname(os.path.abspath(__file__)))
        path = os.path.join(loc, "src/dinsdale_system/input_parameters/A_controllers.txt")
        A = load_matrix_from_file(path)
        self.is_communicating = False
        if A.size:
            self.is_communicating = True
            self.pub_p = rospy.Publisher('~p', numpy_msg(Floats))
            self.neighbours = []
            for i in xrange(A.shape[1]):
                if A[node_number, i] and node_number != i:
                    rospy.Subscriber('controller%s/p' % (i), numpy_msg(Floats), self.neighbour_data_received, i)
                    self.neighbours.append(i)
            self.q = {}
        rospy.Subscriber('controller%s/y' % (node_number), numpy_msg(Floats), self.plant_output_received)

        # Initialize controller
        self.node_number = node_number
        module_name = 'dinsdale_system.controller'
        if node_type != 0:
            module_name += '_' + str(node_type)
        controller_module = importlib.import_module(module_name)
        path = os.path.join(loc, "src/dinsdale_system/input_parameters/T.txt")
        T = load_matrix_from_file(path)
        T = T[0, 0]
        self.controller = controller_module.Controller(node_number, T)

        # Open bag to log data
        bag_name = 'controller_' + str(node_number) + '.bag'
        dir_path = os.path.join(loc, 'bags')
        dir_list = os.listdir(dir_path)
        dir_list = filter(lambda x: os.path.isdir(os.path.join(dir_path, x)), dir_list)
        dir_list.sort(reverse = True)
        newest_dir = dir_list[0]
        self.bag = rosbag.Bag(os.path.join(dir_path, newest_dir, bag_name), 'w')


    def plant_output_received(self, y):
        """ Plant output y is received """

        # Create vector q from received controller data
        if self.is_communicating:
            q_temp = [self.q[i] for i in sorted(self.q)]
            q = np.array([])
            for vector in q_temp:
                q = np.append(q, vector)
            self.controller.q = np.matrix(q)

        # Save data
        self.controller.y = np.mat(y.data).T
        self.bag.write('controller%s/y' % (self.node_number), y)

        # Update controller state
        self.controller.iterate_state()

        # Publish new data
        floats = Floats()
        floats.data = np.reshape(np.array(self.controller.u, dtype = np.float32), self.controller.u.size)
        self.pub_u.publish(floats.data)
        self.bag.write('controller%s/u' % (self.node_number), floats)
        if self.is_communicating:
            self.pub_p.publish(np.reshape(np.array(self.controller.p, dtype = np.float32), self.controller.p.size))


    def neighbour_data_received(self, q, i):
        """ Data q is received from controller i """

        self.q[i] = q.data


# ----------------------------------------------------------------


def main(arguments):
    """ Script entry point """

    node_number = int(arguments[1])
    node_type = int(arguments[2])
    rospy.init_node('controller%s' % (node_number))
    node = ControllerNode(node_number, node_type)
    rospy.spin()
    node.bag.close()


if __name__ == '__main__':
    arguments = rospy.myargv(argv = sys.argv)
    main(arguments)
