#!/usr/bin/env python

import os
import time

def make_dir():
    """ Make directory for data logging """
    time_id = time.strftime('%y%m%d_%H%M%S', time.localtime())
    dir_name = time_id + '_dinsdale'
    loc, f = os.path.split(os.path.dirname(os.path.abspath(__file__)))
    os.mkdir(os.path.join(loc, 'bags', dir_name))

def main():
    """ Setup the simulation """
    make_dir()

if __name__ == '__main__':
    main()
